### PR TITLE
Update activity_restaurant_menu.xml

### PR DESCRIPTION
**Pull request by KartikeySharma**
The problem of overlapping Proceed to Cart button solved

### CODE REVIEW

**Comment by KartikeySharma** [comment]
@AlbinoB Pls have a look at the code. I have also been working on this and this resolved the error

**Comment by AlbinoB** [comment]
Can you explain what the issue was., so I can review it. The ids are all different the the pr you sent.

**Comment by KartikeySharma** [comment]
When we open the restaurant menu fragment and suppose the recycler view has more items than the size of the page.. then when we add an item and the PROCEED TO CART pops up..we can't access the bottom-most item without removing all the upper items from the cart.

**Comment by KartikeySharma** [comment]
The ids have just been short-handed. eg) your textView is txt in my xml

**Comment by KartikeySharma** [comment]
I have also raised an issue in which I have placed the screenshots highlighting the issue. Pls have a look at that too

**Review by AlbinoB — APPROVED** [review]

**Comment by KartikeySharma** [comment]
Great! Thanks a lot.

**Pull request merged**
